export type LanguageCode = 'en' | 'es' | 'fr' | 'zh' | 'de' | 'ja' | 'vi';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文 (简体)', flag: '🇨🇳' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
];

export const UI_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    appTitle: 'InclusiveAlly',
    tagline: 'Personal Decision & 3D Fit Engine',
    advisor: 'AI Decision Advisor',
    fit3d: '3D Fit & Compare',
    timeline: 'Memory Timeline',
    preferences: 'Personal Preferences',
    calendar: 'Calendar & Reminders',
    schedule: 'Decision Schedule',
    privacy: 'Trust & Privacy',
    recordMemory: 'Record Memory',
    voiceNote: 'Voice Note',
    accessibility: 'Accessibility',
    language: 'Language',
    searchPlaceholder: 'Search memories, decisions, sizes, clothing links...',
    req3dFitNotice: 'Paste clothing Product Link (URL) + Size Tag to view on your 3D person',
    pasteUrlAutoExtract: 'Paste URL & Auto-Extract',
    aboutDescription: 'InclusiveAlly helps regular people make smarter decisions, manage project schedules, and remember details, while supporting people with disabilities with adaptive fit, sensory needs, and mobility.',
  },
  es: {
    appTitle: 'InclusiveAlly',
    tagline: 'Motor de Decisión Personal y Ajuste 3D',
    advisor: 'Asesor de Decisiones IA',
    fit3d: 'Ajuste 3D y Comparar',
    timeline: 'Línea de Recuerdos',
    preferences: 'Preferencias Personales',
    calendar: 'Calendario y Recordatorios',
    schedule: 'Programación de Proyectos',
    privacy: 'Confianza y Privacidad',
    recordMemory: 'Grabar Recuerdo',
    voiceNote: 'Nota de Voz',
    accessibility: 'Accesibilidad',
    language: 'Idioma',
    searchPlaceholder: 'Buscar recuerdos, decisiones, tallas, enlaces de ropa...',
    req3dFitNotice: 'Pega el enlace del producto (URL) + talla para ver en tu persona 3D',
    pasteUrlAutoExtract: 'Pegar URL y Extraer',
    aboutDescription: 'InclusiveAlly ayuda a personas a tomar decisiones diarias, gestionar calendarios y recordar detalles, apoyando a personas con discapacidades con ropa adaptativa y necesidades sensoriales.',
  },
  fr: {
    appTitle: 'InclusiveAlly',
    tagline: 'Moteur de Décision Personnelle & Essayage 3D',
    advisor: 'Conseiller IA',
    fit3d: 'Essayage 3D & Comparateur',
    timeline: 'Chronologie des Souvenirs',
    preferences: 'Préférences Personnelles',
    calendar: 'Calendrier & Rappels',
    schedule: 'Planning de Projets',
    privacy: 'Confiance & Confidentialité',
    recordMemory: 'Enregistrer Souvenir',
    voiceNote: 'Note Vocale',
    accessibility: 'Accessibilité',
    language: 'Langue',
    searchPlaceholder: 'Rechercher souvenirs, décisions, tailles, liens vêtements...',
    req3dFitNotice: 'Collez le lien produit (URL) + la taille pour visualiser sur votre mannequin 3D',
    pasteUrlAutoExtract: 'Coller URL & Extraire',
    aboutDescription: 'InclusiveAlly aide à prendre des décisions quotidiennes, gérer des projets et se souvenir de tout, en soutenant les personnes en situation de handicap avec des fonctionnalités adaptatives.',
  },
  zh: {
    appTitle: 'InclusiveAlly',
    tagline: '个人决策与3D试衣助手',
    advisor: 'AI 决策顾问',
    fit3d: '3D试衣与比对',
    timeline: '记忆时间轴',
    preferences: '个人偏好与尺寸',
    calendar: '日历与提醒',
    schedule: '项目日程规划',
    privacy: '信任与隐私',
    recordMemory: '记录记忆',
    voiceNote: '语音笔记',
    accessibility: '无障碍辅助',
    language: '语言',
    searchPlaceholder: '搜索记忆、决策、尺寸、服装链接...',
    req3dFitNotice: '请输入服装商品链接 (URL) 和尺寸标签，即可在3D真人模型上进行试衣',
    pasteUrlAutoExtract: '粘贴链接并自动解析',
    aboutDescription: 'InclusiveAlly 为所有人提供智能日常决策、项目日程规划和记忆支持，同时为残障人士提供无障碍服装与感官适应性支持。',
  },
  de: {
    appTitle: 'InclusiveAlly',
    tagline: 'Persönlicher Entscheidungs- & 3D-Passform-Assistent',
    advisor: 'KI-Entscheidungsberater',
    fit3d: '3D-Passform & Vergleich',
    timeline: 'Erinnerungs-Timeline',
    preferences: 'Persönliche Präferenzen',
    calendar: 'Kalender & Erinnerungen',
    schedule: 'Projekt-Ablaufplan',
    privacy: 'Vertrauen & Datenschutz',
    recordMemory: 'Erinnerung Speichern',
    voiceNote: 'Sprachnotiz',
    accessibility: 'Barrierefreiheit',
    language: 'Sprache',
    searchPlaceholder: 'Erinnerungen, Entscheidungen, Größen, Bekleidungs-Links suchen...',
    req3dFitNotice: 'Produkt-Link (URL) + Größe eingeben, um sie an der 3D-Figur anzusehen',
    pasteUrlAutoExtract: 'URL Einfügen & Extrahieren',
    aboutDescription: 'InclusiveAlly unterstützt alltägliche Entscheidungen, Projektplanung und Gedächtnis, und bietet Menschen mit Behinderungen barrierefreie Anpassungen.',
  },
  ja: {
    appTitle: 'InclusiveAlly',
    tagline: '意思決定＆3Dフィットアシスタント',
    advisor: 'AI意思決定アドバイザー',
    fit3d: '3D試着＆比較',
    timeline: 'メモリータイムライン',
    preferences: '個人設定＆サイズ',
    calendar: 'カレンダー＆リマインダー',
    schedule: 'プロジェクトスケジュール',
    privacy: '信頼＆プライバシー',
    recordMemory: 'メモリーを記録',
    voiceNote: '音声メモ',
    accessibility: 'アクセシビリティ',
    language: '言語',
    searchPlaceholder: 'メモリー、決定、サイズ、服のURLを検索...',
    req3dFitNotice: '3Dアバターで試着するには、服のURLとサイズを入力してください',
    pasteUrlAutoExtract: 'URL貼り付け＆自動抽出',
    aboutDescription: 'InclusiveAllyは日常の意思決定、プロジェクトの管理、メモリー保持を助け、障害を持つ方向けのアダプティブ機能も提供します。',
  },
  vi: {
    appTitle: 'InclusiveAlly',
    tagline: 'Hệ thống Đưa ra Quyết định & Thử đồ 3D',
    advisor: 'Cố vấn Quyết định AI',
    fit3d: 'Thử đồ 3D & So sánh',
    timeline: 'Dòng thời gian Ký ức',
    preferences: 'Sở thích & Kích thước',
    calendar: 'Lịch & Nhắc nhở',
    schedule: 'Lịch trình Dự án',
    privacy: 'Bảo mật & Quyền riêng tư',
    recordMemory: 'Ghi ký ức',
    voiceNote: 'Ghi âm',
    accessibility: 'Hỗ trợ tiếp cận',
    language: 'Ngôn ngữ',
    searchPlaceholder: 'Tìm kiếm ký ức, quyết định, kích cỡ, link quần áo...',
    req3dFitNotice: 'Dán đường dẫn sản phẩm (URL) + Kích cỡ để xem trên người 3D của bạn',
    pasteUrlAutoExtract: 'Dán URL & Tự động trích xuất',
    aboutDescription: 'InclusiveAlly giúp mọi người đưa ra quyết định hàng ngày, quản lý lịch trình dự án, đồng thời hỗ trợ người khuyết tật với nhu cầu thời trang thích ứng.',
  },
};
